language: php
php:
  - '7.3'
  
  # Instalar dependencias
  install:
    - composer install

dist: bionic


# Configurar el servidor Tomcat embebido
services:
  - docker
  - mysql
  - postgresql

before_script:
  -cp .env.example .env
  - mysql -e 'create database conversordb;'
  - composer self-update
  - composer install --no-interaction --prefer-source 
  - php artisan key:generate
  - php artisan migrate

notifications:
    on_success: never
    on_failure: always


# Compilar y ejecutar pruebas
script:
  - vendor/bin/phpunit
  

# Despliegue de la aplicación en Tomcat
after_success:
  - docker run -d --name tomcat-container -p 8080:8080 -v $TRAVIS_BUILD_DIR/src/main/webapp/:/usr/local/tomcat/webapps/ tomcat:latest
